### ISSUE TITLE
Template autoimport

### ISSUE THREAD

**Issue by jangaraj** [Goodsmileduck/zabbix-docker#1]
Try to change:
```
  zabbix-server:
    container_name: zabbix-server
    image: monitoringartist/zabbix-xxl
    ports:
      - 80:80
      - 443:443
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZS_DBHost=zabbix-db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=my_password
```
to:
```  
  zabbix-server:
    container_name: zabbix-server
    image: monitoringartist/zabbix-xxl
    ports:
      - 80:80
      - 443:443
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - <PATH>/templates:/etc/zabbix/api/mytemplates:ro
    environment:
      - ZS_DBHost=zabbix-db
      - ZS_DBUser=zabbix
     - ZS_DBPassword=my_password
```
and your `.xml` templates from that mounted folder should be imported automatically, See code:
https://github.com/monitoringartist/zabbix-xxl/blob/8f6622365383c776186399a664da0446876faf28/Dockerfile/zabbix-xxl/container-files-zabbix-xxl/config/init/11-xxl.sh#L112-L120
